package org.vestifeed.ui.icons

/**
 * The Material Symbols glyphs the app draws, addressed by their Unicode
 * codepoints in the font's private-use area. The bundled font
 * (`composeResources/font/material_symbols.ttf`) is a subset containing exactly
 * these glyphs, so the app ships a ~40 KB icon font rather than the ~10 MB full
 * variable font.
 *
 * Codepoints are stable across Material Symbols releases; the names match the
 * upstream ligature names.
 */
object MaterialSymbols {
    const val ArrowBack = "\uE5C4"
    const val ChevronRight = "\uE5CC"
    const val MoreVert = "\uE5D4"
    const val Warning = "\uE002"
    const val Search = "\uE8B6"
    const val Newspaper = "\uEB81"
    const val ListAlt = "\uE0EE"
    const val Bookmark = "\uE866"
    const val BookmarkAdd = "\uE598"
    const val BookmarkAdded = "\uE599"
    const val Close = "\uE14C"
    const val RssFeed = "\uE0E5"
    const val Settings = "\uE8B8"
    const val Tune = "\uE429"
    const val Refresh = "\uE5D5"
    const val Add = "\uE145"
    const val OpenInNew = "\uE895"
    const val OpenInBrowser = "\uE89D"
    const val Share = "\uE80D"
    const val MarkEmailRead = "\uE9FD"
    const val MarkEmailUnread = "\uF18A"
    const val Save = "\uE161"
    const val Delete = "\uE872"
    const val Download = "\uE171"
    const val Upload = "\uE2C6"
    const val PlayArrow = "\uE037"
    const val Stop = "\uE047"

    // Settings.
    const val Visibility = "\uE8F4"
    const val VisibilityOff = "\uE8F5"
    const val Image = "\uE251"
    const val Crop = "\uE3BE"
    const val Notes = "\uE26C"
    const val Person = "\uE7FD"
    const val Headphones = "\uE310"
    const val Sync = "\uE627"
    const val Schedule = "\uE192"
    const val Label = "\uE892"
    const val Podcasts = "\uF048"
    const val Dns = "\uE875"
    const val Link = "\uE157"
    const val Logout = "\uE9BA"
    const val ViewList = "\uE8EF"
    const val GridView = "\uE9B0"

    // Curated-catalog topic badges.
    const val Android = "\uE859"
    const val Code = "\uE86F"
    const val Pets = "\uE91D"
    const val LaptopMac = "\uE320"
    const val Architecture = "\uEA3B"
    const val Spa = "\uEB4C"
    const val MenuBook = "\uEA19"
    const val TrendingUp = "\uE8E5"
    const val DirectionsCar = "\uE531"
    const val Chess = "\uF5E7"
    const val SportsCricket = "\uEA27"
    const val CurrencyBitcoin = "\uEBC5"
    const val Security = "\uE32A"
    const val Handyman = "\uF10B"
    const val Eco = "\uEA35"
    const val Checkroom = "\uF19E"
    const val Restaurant = "\uE56C"
    const val SportsSoccer = "\uEA2F"
    const val SentimentVerySatisfied = "\uE815"
    const val SportsEsports = "\uE6EC"
    const val HistoryEdu = "\uEA3E"
    const val Chair = "\uEFED"
    const val DesktopMac = "\uE30B"
    const val Mood = "\uE24E"
    const val Movie = "\uE02C"
    const val MusicNote = "\uE3A1"
    const val Park = "\uEA63"
    const val Savings = "\uE2EB"
    const val PhotoCamera = "\uE3B0"
    const val Terminal = "\uEB8E"
    const val Science = "\uEA4B"
    const val RocketLaunch = "\uEB9B"
    const val SportsBasketball = "\uEA26"
    const val Lightbulb = "\uE0F0"
    const val Memory = "\uE322"
    const val Tv = "\uE333"
    const val SportsTennis = "\uEA32"
    const val Flight = "\uE539"
    const val DesignServices = "\uF10A"
    const val Web = "\uE051"
}
