import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
}

kotlin {
    jvmToolchain(17)

    compilerOptions {
        freeCompilerArgs.add("-Xannotation-default-target=param-property")
    }
}

// AGP doesn't expose `local.properties` as Gradle project properties in
// 9.x, so we load it explicitly with the standard `java.util.Properties`
// API. `local.properties` is auto-generated by Android Studio (with
// `sdk.dir`) and is gitignored, so it's the conventional home for
// credentials that must never enter version control.
val keystorePropertiesFile = rootProject.file("local.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) {
        keystorePropertiesFile.inputStream().use { load(it) }
    }
}
val keystorePath = keystoreProperties.getProperty("storeFile")?.let(::file)

android {
    namespace = "org.vestifeed"

    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "org.vestifeed"
        minSdk = 34
        targetSdk = 37
        versionCode = 24
        versionName = "0.4.3"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        create("release") {
            storeFile = keystorePath
            storePassword = keystoreProperties.getProperty("storePassword")
            keyAlias = keystoreProperties.getProperty("keyAlias")
            keyPassword = keystoreProperties.getProperty("keyPassword")
                ?: keystoreProperties.getProperty("storePassword")
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
        }

        release {
            signingConfig = signingConfigs.getByName("release")

            isMinifyEnabled = true
            isShrinkResources = true

            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt")
            )
        }

        create("nightly") {
            initWith(getByName("release"))
            applicationIdSuffix = ".nightly"
        }
    }

    buildFeatures {
        buildConfig = true
    }

    testOptions {
        unitTests {
            isReturnDefaultValues = true
        }
    }

    lint {
        disable += "GradleDependency"
    }
}

dependencies {
    implementation(project(":shared"))
    implementation(project(":ui"))

    // Coroutines
    implementation(libs.kotlinx.coroutines)

    // AndroidX
    implementation(libs.androidx.sqlite.framework)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.activity.compose)

    // Material Components themes the host; Compose Material3 draws the UI.
    implementation(libs.material)
    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.work)
    implementation(libs.androidx.browser)
    androidTestImplementation(libs.androidx.work.testing)

    // Unit tests
    testImplementation(libs.junit)

    // Instrumented tests
    androidTestImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(libs.androidx.test.espresso.core)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
